-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 15:51:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produkt` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `ProductCategory_id` INT NULL,
  PRIMARY KEY (`id`, `ProductCategory_id`),
  INDEX `fk_Product_ProductCategory_idx` (`ProductCategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_ProductCategory`
    FOREIGN KEY (`ProductCategory_id`)
    REFERENCES `mydb`.`ProductCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Postal-Code` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `orderDate` TIMESTAMP NOT NULL,
  `deliveryDate` TIMESTAMP GENERATED ALWAYS AS (0) VIRTUAL,
  `Customer_id` INT NULL,
  PRIMARY KEY (`id`, `Customer_id`),
  INDEX `fk_Order_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Order` (
  `Product_id` INT NULL,
  `Product_ProductCategory_id` INT NULL,
  `Order_id` INT NULL,
  `Order_Customer_id` INT NULL,
  PRIMARY KEY (`Product_id`, `Product_ProductCategory_id`, `Order_id`, `Order_Customer_id`),
  INDEX `fk_Product_has_Order_Order1_idx` (`Order_id` ASC, `Order_Customer_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Order_Product1_idx` (`Product_id` ASC, `Product_ProductCategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Order_Product1`
    FOREIGN KEY (`Product_id` , `Product_ProductCategory_id`)
    REFERENCES `mydb`.`Product` (`id` , `ProductCategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Order_Order1`
    FOREIGN KEY (`Order_id` , `Order_Customer_id`)
    REFERENCES `mydb`.`Order` (`id` , `Customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Order1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Order1` (
  `Product_id` INT NOT NULL,
  `Order_id` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Order_id`),
  INDEX `fk_Product_has_Order1_Order1_idx` (`Order_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Order1_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Order1_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Order1_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `mydb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
